apiVersion: v1
kind: Service
metadata:
  name: sc-scan
  namespace: dev
  labels:
    app: sc-scan
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
      protocol: TCP
  selector:
    app: sc-scan
